synonyms = {
    'gld': 'gold',
    'slv': 'silver',
    'oil': 'oil',
    '₿': 'bitcoin',
    'btc': 'bitcoin',
    'xbt': 'bitcoin',
    'xrp': 'ripple',
    'xlm': 'stellar',
    'ltc': 'litecoin',
    'xmr': 'monero',
    'eth': 'ethereum',
    'ether': 'ethereum',
    'etherium': 'ethereum',
    'ada': 'cardano',
    'bb': 'blackberry',
    'pltr': 'palantir',
    'ptlr': 'palantir',
    'gme': 'gamestop',
    'tsla': 'tesla',
    'tlry': 'tilray',
    'nvda': 'nvidia',
    'aapl': 'apple',
    'appl': 'apple',
    'msft': 'microsoft',
    'fb':  'facebook',
    'goog': 'google',
    'baba': 'alibaba',
    'wmt': 'wallmart',
    'amzn': 'amazon',
    'jpm': 'jpmorgan',
    'sndl': 'sundial',
    'nok': 'nokia',
    'nkla': 'nikola',
    'pton': 'peloton',
    'brk.a': 'berkshire',
    'brk.b': 'berkshire',
    'blk': 'blackrock',
    'nflx': 'netflix',
    'twtr': 'twitter',
    'snap': 'snapchat',
    'htz': 'hertz',
    'htzgq': 'hertz',
    'rh': 'robinhood',
    'bidu': 'baidu',
    # 'f': 'ford',
    # 'bch': 'bitcoin_cash',
    # 'algo': 'algorand',
    # 'gm': 'generalmotors'
}